spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"
  jackson: 
    time-zone: America/Sao_Paulo
    default-property-inclusion: NON_ABSENT  
    deserialization:      
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true      
    locale: en_US    
springdoc:
  cache:
    disabled: true
  swagger-ui:
    use-root-path: true
    operationsSorter: alpha
    tagsSorter: alpha
    doc-expansion: none
app:
  version: 0.0.1
  name: Escritótio
  description: Gerenciamento de escritótio   
---     
spring:
  config:
    activate:
      on-profile: dev  
  datasource:
    url: jdbc:postgresql://localhost:58620/mydatabase
    driverClassName: org.postgresql.Driver
    username: myuser
    password: secret 
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect   
    properties:
      hibernate: 
        "[format_sql]": true    
    hibernate:
      ddl-auto: create     
---     
spring:
  config:
    activate:
      on-profile: h2  
  datasource:
    url: jdbc:h2:mem:testdb;
    driverClassName: org.h2.Driver
    username: sa
    password:      
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect   
    properties:
      hibernate: 
        "[format_sql]": true    
    hibernate:
      ddl-auto: create-drop
  h2:
    console.enabled: true      
logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
        security: DEBUG
        boot:
#          autoconfigure: DEBUG
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE       
  


   