/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/roles/{id}": {
    get: operations["getById"];
    put: operations["update"];
    delete: operations["deleteById"];
  };
  "/api/roles": {
    get: operations["list"];
    post: operations["create"];
  };
  "/api/auth/token": {
    post: operations["token"];
  };
  "/api/auth/register": {
    post: operations["create_1"];
  };
  "/api/auth": {
    get: operations["list_1"];
  };
  "/api/auth/profile": {
    get: operations["profile"];
  };
  "/api/admin/users": {
    get: operations["list_2"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Role: {
      /** Format: int64 */
      id?: number;
      name: string;
      description: string;
      /** Format: date-time */
      createAt?: string;
      /** Format: date-time */
      updateAt?: string;
    };
    LoginReq: {
      email: string;
      password: string;
    };
    CustomUserDetails: {
      password?: string;
      username?: string;
      accountNonExpired?: boolean;
      accountNonLocked?: boolean;
      credentialsNonExpired?: boolean;
      enabled?: boolean;
      /** Format: int64 */
      id?: number;
      name?: string;
      email?: string;
      token?: string;
      roles?: string[];
    };
    RegisterDTO: {
      name: string;
      email: string;
      password: string;
    };
    User: {
      /** Format: int64 */
      id?: number;
      email: string;
      name: string;
      roles?: string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  getById: {
    parameters: {
      path: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Role"];
        };
      };
    };
  };
  update: {
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Role"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Role"];
        };
      };
    };
  };
  deleteById: {
    parameters: {
      query: {
        id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  list: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["Role"][];
        };
      };
    };
  };
  create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["Role"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  token: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginReq"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CustomUserDetails"];
        };
      };
    };
  };
  create_1: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegisterDTO"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["User"];
        };
      };
    };
  };
  list_1: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["User"][];
        };
      };
    };
  };
  profile: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["User"];
        };
      };
    };
  };
  list_2: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["User"][];
        };
      };
    };
  };
}
